on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Test
        run: |
          echo $RELEASE_VERSION
      - name: Test2
        run: |
          echo ${{ env.RELEASE_VERSION }}
      - name: Test3
        run: |
          echo $env.RELEASE_VERSION
